/**
 * Service Worker Registration with Update Handling
 *
 * Registers the service worker generated by vite-plugin-pwa and handles updates.
 */

export function registerServiceWorker() {
  if ('serviceWorker' in navigator && import.meta.env.PROD) {
    // In production, vite-plugin-pwa automatically registers the service worker
    // via the generated sw.js file. This function exists for compatibility.

    window.addEventListener('load', () => {
      navigator.serviceWorker
        .register('/sw.js')
        .then((registration: ServiceWorkerRegistration) => {
          console.log('Service Worker registered:', registration);

          // Check for updates every hour
          setInterval(
            () => {
              registration.update();
            },
            60 * 60 * 1000,
          );

          // Check for updates
          registration.addEventListener('updatefound', () => {
            const newWorker = registration.installing;
            if (newWorker) {
              newWorker.addEventListener('statechange', () => {
                if (newWorker.state === 'installed' && navigator.serviceWorker.controller) {
                  // New content available
                  const updateConfirmed = confirm(
                    'A new version is available! Click OK to update.',
                  );
                  if (updateConfirmed) {
                    window.location.reload();
                  }
                }
              });
            }
          });
        })
        .catch((error: Error) => {
          console.error('Service Worker registration failed:', error);
        });
    });

    // Manual update check on visibility change
    document.addEventListener('visibilitychange', () => {
      if (!document.hidden) {
        navigator.serviceWorker.getRegistration().then((registration) => {
          if (registration) {
            registration.update();
          }
        });
      }
    });
  }
}
